local el3 = elements.allocate("EXPLOSIVE", "MTHL")
elements.property(el3,"Advection",0.9)
elements.property(el3,"Loss",0.95)
elements.property(el3,"Collision",-0.1)
elements.property(el3,"Gravity",0.1)
elements.property(el3,"Flammable",100)
elements.property(el3,"Meltable",0)
elements.property(el3,"Hardness",3)
elements.property(el3,"Weight",20)
elements.property(el3,"Description","Methane liquid. Under development")
elements.property(el3,"State",ST_SOLID)
elements.property(el3,"Properties",TYPE_PART)
elements.property(el3,"Colour","0xccff00")
elements.property(el3,"Name","MTHL")
elements.property(el3,"MenuVisible",1)
elements.property(el3,"MenuSection",7)
elements.property(el3,"Falldown",2)
elements.property(el3,"Explosive",99)
local el = elements.allocate("EXPLOSIVE", "MTHN")
elements.property(el,"Advection",0.9)
elements.property(el,"Loss",0.95)
elements.property(el,"Collision",-0.1)
elements.property(el,"Gravity",0.0)
elements.property(el,"Flammable",100)
elements.property(el,"Meltable",0)
elements.property(el,"Hardness",3)
elements.property(el,"Weight",0)
elements.property(el,"Description","Methane. Explosive gas. Flammable. Under development")
elements.property(el,"State",ST_SOLID)
elements.property(el,"Properties",TYPE_PART)
elements.property(el,"Colour","0xccff00")
elements.property(el,"Name","MTHN")
elements.property(el,"MenuVisible",1)
elements.property(el,"MenuSection",6)
elements.property(el,"Falldown",1)
elements.property(el,"Diffusion",1)
elements.property(el,"Explosive",99)
elements.property(el, 'LowTemperature', '-1.0')
elements.property(el, "LowTemperatureTransition", el3)
local el2 = elements.allocate("GAS", "ARGN")
elements.property(el2,"Advection",0.9)
elements.property(el2,"Loss",0.95)
elements.property(el2,"Collision",-0.1)
elements.property(el2,"Gravity",0.0)
elements.property(el2,"Flammable",0)
elements.property(el2,"Meltable",0)
elements.property(el2,"Hardness",3)
elements.property(el2,"Weight",0)
elements.property(el2,"Description","Argonium. Simple gas. Non flammable. When combined with OXYG turns into AIR. Under development")
elements.property(el2,"State",ST_SOLID)
elements.property(el2,"Properties",TYPE_PART)
elements.property(el2,"Colour","0xccccff")
elements.property(el2,"Name","ARGN")
elements.property(el2,"MenuVisible",1)
elements.property(el2,"MenuSection",6)
elements.property(el2,"Falldown",1)
elements.property(el2,"Diffusion",1)
elements.property(el2,"Explosive",0)
local el2 = elements.allocate("GAS", "AIR")
elements.property(el2,"Advection",0.9)
elements.property(el2,"Loss",0.95)
elements.property(el2,"Collision",-0.1)
elements.property(el2,"Gravity",0.0)
elements.property(el2,"Flammable",0)
elements.property(el2,"Meltable",0)
elements.property(el2,"Hardness",3)
elements.property(el2,"Weight",0)
elements.property(el2,"Description","Air")
elements.property(el2,"State",ST_SOLID)
elements.property(el2,"Properties",TYPE_PART)
elements.property(el2,"Colour","0xffffff")
elements.property(el2,"Name","AIR")
elements.property(el2,"MenuVisible",1)
elements.property(el2,"MenuSection",6)
elements.property(el2,"Falldown",1)
elements.property(el2,"Diffusion",1)
elements.property(el2,"Explosive",0)
function argonium(index, partx, party, surround_space, nt)
  if nt > 0 then 
    for ri, rx, ry in sim.neighbours(partx, party, 1) do
      local Tp = sim.partProperty(ri, "type")
      if Tp == elements.DEFAULT_PT_O2 then
      Tp = elements.DEFAULT_PT_DUST
      end
    end
  end
end
elements.property(el2,"Update",argonium)