local rnd=math.random(1,4)
tpt.message_box("Mo'Bombs V 0.0.7")
elements.property(elements.DEFAULT_PT_NBLE,"Name","HLUM")
elements.property(elements.DEFAULT_PT_NBLE,"Colour","0x0000ff")
elements.property(elements.DEFAULT_PT_NBLE,"Description","Helium. Conductive, Ionizes into plasma when sparked.")

elements.property(elements.DEFAULT_PT_LOVE,"MenuVisible",1)
elements.property(elements.DEFAULT_PT_LOVE,"MenuSection",11)
elements.property(elements.DEFAULT_PT_LOLZ,"MenuVisible",1)
elements.property(elements.DEFAULT_PT_LOLZ,"MenuSection",11)
elements.property(elements.DEFAULT_PT_EMBR,"MenuVisible",1)
elements.property(elements.DEFAULT_PT_EMBR,"MenuSection",5)
elements.property(elements.DEFAULT_PT_MORT,"MenuVisible",1)
elements.property(elements.DEFAULT_PT_MORT,"MenuSection",11)

local el = elements.allocate("EXPLOSIVE", "PWEX")
elements.property(el,"Advection",0.4)
elements.property(el,"Loss",0.95)
elements.property(el,"Collision",-0.1)
elements.property(el,"Gravity",0.1)
elements.property(el,"Flammable",100)
elements.property(el,"Meltable",0)
elements.property(el,"Hardness",3)
elements.property(el,"Weight",99)
elements.property(el,"Description","Explosive powder. Flammable")
elements.property(el,"State",ST_SOLID)
elements.property(el,"Properties",TYPE_PART)
elements.property(el,"Colour","0xff0000")
elements.property(el,"Name","PWDE")
elements.property(el,"MenuVisible",1)
elements.property(el,"MenuSection",5)
elements.property(el,"Falldown",1)
elements.property(el,"Explosive",99)
local el2 = elements.allocate("EXPLOSIVE", "FLTE")
elements.property(el,"Properties",TYPE_PART)
elements.property(el2,"Advection",0.4)
elements.property(el2,"Loss",0)
elements.property(el2,"Collision",0)
elements.property(el2,"Gravity",0)
elements.property(el2,"Flammable",100)
elements.property(el2,"Meltable",1)
elements.property(el2,"Hardness",3)
elements.property(el2,"Weight",0)
elements.property(el2,"Description","No-gravity explosive.")
elements.property(el2,"State",ST_SOLID)
elements.property(el2,"Colour","0x0000ff")
elements.property(el2,"Name","FLTE")
elements.property(el2,"MenuVisible",1)
elements.property(el2,"MenuSection",5)
elements.property(el2,"Falldown",0)
elements.property(el2,"Explosive",900)
elements.property(el2,"LowTemperature",ITH)
local el3 = elements.allocate("EXPLOSIVE", "BPWD")
elements.property(el3,"Advection",0.4)
elements.property(el3,"Loss",0.95)
elements.property(el3,"Collision",-0.1)
elements.property(el3,"Gravity",0.1)
elements.property(el3,"Flammable",25)
elements.property(el3,"Meltable",0)
elements.property(el3,"Hardness",3)
elements.property(el3,"Weight",98)
elements.property(el3,"Description","Black powder. Basic explosive")
elements.property(el3,"State",ST_SOLID)
elements.property(el3,"Colour","0x0f0f0f")
elements.property(el3,"Name","BPWD")
elements.property(el3,"MenuVisible",1)
elements.property(el3,"MenuSection",5)
elements.property(el3,"Falldown",1)
elements.property(el3,"Explosive",5)
local el4 = elements.allocate("EXPLOSIVE", "NCLS")
elements.property(el4,"Advection",0)
elements.property(el4,"Loss",1)
elements.property(el4,"Collision",0)
elements.property(el4,"Gravity",0)
elements.property(el4,"Flammable",25)
elements.property(el4,"Meltable",0)
elements.property(el4,"Hardness",100)
elements.property(el4,"Weight",5)
elements.property(el4,"Description","Nitrocellulose. Pressure sensitive.Not completed yet")
elements.property(el4,"State",ST_SOLID)
elements.property(el4,"Colour","0xffffff")
elements.property(el4,"Name","NCLS")
elements.property(el4,"MenuVisible",1)
elements.property(el4,"MenuSection",5)
elements.property(el4,"Falldown",0)
elements.property(el4,"Explosive",90)
local el5 = elements.allocate("EXPLOSIVE", "MLTV")
elements.property(el5,"Advection",0)
elements.property(el5,"Loss",1)
elements.property(el5,"Collision",-0.1)
elements.property(el5,"Gravity",0.1)
elements.property(el5,"Flammable",4)
elements.property(el5,"Meltable",0)
elements.property(el5,"Hardness",1)
elements.property(el5,"Weight",5)
elements.property(el5,"Description","Molotov cocktail. Flammable liquid, Slowly burning.")
elements.property(el5,"State",ST_LIQUID)
elements.property(el5,"Colour","0x333300")
elements.property(el5,"Name","MLTV")
elements.property(el5,"MenuVisible",1)
elements.property(el5,"MenuSection",5)
elements.property(el5,"Falldown",2)
elements.property(el5,"Explosive",0)
local el6 = elements.allocate("EXPLOSIVE", "ALCH")
elements.property(el6,"Advection",0)
elements.property(el6,"Loss",1)
elements.property(el6,"Collision",-0.1)
elements.property(el6,"Gravity",0.1)
elements.property(el6,"Flammable",100)
elements.property(el6,"Meltable",0)
elements.property(el6,"Hardness",1)
elements.property(el6,"Weight",5)
elements.property(el6,"Description","Alcohol. Flammable liquid, Fast burning.")
elements.property(el6,"State",ST_LIQUID)
elements.property(el6,"Colour","0xCCFFFF")
elements.property(el6,"Name","ALCH")
elements.property(el6,"MenuVisible",1)
elements.property(el6,"MenuSection",5)
elements.property(el6,"Falldown",2)
elements.property(el6,"Explosive",2)
local el7 = elements.allocate("EXPLOSIVE", "SMTR")
elements.property(el7,"Advection",1)
elements.property(el7,"Loss",1)
elements.property(el7,"Collision",-0.1)
elements.property(el7,"Meltable",0)
elements.property(el7,"Hardness",0)
elements.property(el7,"Description","Strange matter. Totally random element. I can't say nothing about it but it's a powder. Not complete yet")
elements.property(el7,"Name","SMTR")
elements.property(el7,"MenuVisible",1)
elements.property(el7,"MenuSection",5)

function rand()

rnd=math.random(1,4)
if rnd == 1 then
elements.property(el7,"Colour","0x00FF00")
rnd=math.random(1,4)
end
if rnd == 2 then
elements.property(el7,"Colour","0xffffff")
rnd=math.random(1,4)
end
if rnd ==3 then
elements.property(el7,"Colour","0x0f00cf")
rnd=math.random(1,4)
end

if rnd ==1 then
elements.property(el7,"State",ST_GAS)
rnd=math.random(1,4)
end
if rnd == 2 then
elements.property(el7,"State",ST_LIQUID)
rnd=math.random(1,4)
end
if rnd ==3 then
elements.property(el7,"State",ST_POWDER)
rnd=math.random(1,4)
end
elements.property(el7,"Gravity",math.random(0,0.1))
elements.property(el7,"Flammable",(math.floor(math.random(0,999))))
elements.property(el7,"Weight",(math.floor(math.random(0,99))))
elements.property(el7,"Gravity",math.random(0,0.1))
elements.property(el7,"Flammable",(math.floor(math.random(0,999))))
elements.property(el7,"Falldown",2)
elements.property(el7,"Explosive",(math.floor(math.random(0,1))))
end
rand()
tpt.register_step(rand())
rand()